import { colors } from "@/app/src/Theme/color";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  phoneShell: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 32,
    overflow: "hidden",
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  screenScrollContent: {
    paddingBottom: 28,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  topBarLabel: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: "600",
  },
  screenIntro: {
    marginTop: 18,
    marginBottom: 12,
    gap: 6,
  },
  screenIntroRtl: {
    alignItems: "flex-end",
  },
  screenEyebrow: {
    color: "#8c8c8c",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  screenDescription: {
    color: "#111111",
    fontSize: 18,
    lineHeight: 26,
    fontWeight: "500",
  },
  taskCard: {
    backgroundColor: "#fcfcfc",
    padding: 16,
    borderRadius: 20,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "#f0f0f0",
  },
  taskCardRtl: {
    flexDirection: "row-reverse",
  },
  taskTitle: {
    fontSize: 17,
    fontWeight: "600",
    color: "#111111",
  },
  taskHeader: {
    gap: 4,
    marginBottom: 18,
  },
  taskHeaderRtl: {
    alignItems: "flex-end",
  },
  sectionEyebrow: {
    color: "#8c8c8c",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  screenTitle: {
    color: "#111111",
    fontSize: 28,
    fontWeight: "600",
  },
  taskMeta: {
    color: "#111111",
    fontSize: 17,
    fontWeight: "500",
  },
  taskHint: {
    color: "#8c8c8c",
    fontSize: 14,
    lineHeight: 20,
  },
  composerCard: {
    backgroundColor: "#fcfcfc",
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "#f0f0f0",
    marginBottom: 20,
  },
  composerCardRtl: {
    alignItems: "flex-end",
  },
  composerTitle: {
    color: "#111111",
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 4,
  },
  composerSubtitle: {
    color: "#8c8c8c",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
  },
  textInput: {
    backgroundColor: "#f8f8f8",
    color: "#111111",
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#ececec",
    minHeight: 92,
    textAlignVertical: "top",
    fontSize: 16,
  },
  textInputRtl: {
    textAlign: "right",
    writingDirection: "rtl",
  },
  addButton: {
    backgroundColor: "#111111",
    alignItems: "center",
    borderRadius: 16,
    paddingVertical: 14,
    marginTop: 12,
  },
  addButtonDisabled: {
    backgroundColor: "#b8b8b8",
  },
  addButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },
  listContent: {
    flexGrow: 1,
    paddingBottom: 10,
  },
  emptyStateRtl: {
    alignItems: "flex-end",
  },
  emptyState: {
    backgroundColor: "#fcfcfc",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#f0f0f0",
    paddingHorizontal: 18,
    paddingVertical: 28,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  emptyIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#f4f4f5",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  emptyTitle: {
    color: "#111111",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 6,
  },
  emptySubtitle: {
    color: "#8c8c8c",
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    marginBottom: 18,
  },
  emptyButton: {
    backgroundColor: "#111111",
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
  },
  emptyButtonText: {
    color: "#ffffff",
    fontWeight: "700",
  },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#111111",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxCompleted: {
    backgroundColor: "#111111",
    borderColor: "#111111",
  },
  taskBody: {
    flex: 1,
    gap: 4,
  },
  taskBodyRtl: {
    alignItems: "flex-end",
  },
  taskTitleCompleted: {
    textDecorationLine: "line-through",
    color: "#8c8c8c",
  },
  taskStatus: {
    color: "#8c8c8c",
    fontSize: 13,
    fontWeight: "500",
  },
  deleteButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#111111",
    alignItems: "center",
    justifyContent: "center",
  },
  textLtr: {
    textAlign: "left",
    writingDirection: "ltr",
  },
  textRtl: {
    textAlign: "right",
    writingDirection: "rtl",
  },
});
